### ISSUE TITLE
Solo una piccola cosa sul tipo

### ISSUE THREAD

**Issue by slendy98DX** [fconsiglio98/kanto-dex#1]
@Json(name = "types")
 val types: MutableList<String>

Io avrei fatto una List<String>,dato che i tipi di un Pokémon vengono generati seguendo il JSON,e quelli sono sempre fissi. Non c'è dunque secondo me bisogno di instanziarli come MutableList.

**Comment by fconsiglio98** [comment]
è necessario che siano in una MutableList in quanto effettuo dei controlli e dei cambiamenti come nel caso in cui il pokemon sia di tipo elettro o lotta, non sono riuscito a fare entrare l'intera parola (inglese) nelle view dei tipi e ho dovuto abbreviarli (cosa che viene fatta anche in alcuni giochi) manualmente.

**Comment by slendy98DX** [comment]
vero,sorry
