### ISSUE TITLE
Colore del tipo veleno diverso tra layout portrait e landscape

### ISSUE THREAD

**Issue by slendy98DX** [fconsiglio98/kanto-dex#2]
Alla rotazione dello schermo, ho notato questo cambiamento di colore del tipo veleno quando esso è type2. Ho testato con i monotype veleno, e il problema non sussiste.

**Comment by slendy98DX** [comment]
Stessa cosa succede col ground type (prova geodude per esempio)

**Comment by slendy98DX** [comment]
Dopo un'attenta analisi, pare che il tipo secondario di tutti i pokemon dual type diventi di un colore blu scuro quando in landscape mode.

**Comment by fconsiglio98** [comment]
Issue risolta. Era dovuta a un backgroundTint dimenticato lì.
